version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet
    depends_on:
      myapp:
        condition: service_healthy

  myapp:
    build:
      context: .
    container_name: myapp
    tty: true
    ports:
      - "3000:3000"
    networks:
      - appnet
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdatabase
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - appnet
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  appnet:
    driver: bridge

volumes:
  mysql_data:
  node_modules:
